"""add_scheduled_for_date_to_tasks

Revision ID: 91155436e1ab
Revises: 449c47d6520c
Create Date: 2025-08-10 21:20:51.505231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91155436e1ab'
down_revision: Union[str, Sequence[str], None] = '449c47d6520c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('scheduled_for_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'scheduled_for_date')
    # ### end Alembic commands ###
