"""update_job_metrics_ai_analysis

Revision ID: 96cf94b401ab
Revises: ac661e467e04
Create Date: 2025-08-08 23:32:25.104750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96cf94b401ab'
down_revision: Union[str, Sequence[str], None] = 'ac661e467e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_metrics', sa.Column('ai_analysis', sa.JSON(), nullable=True))
    op.drop_column('job_metrics', 'opportunities')
    op.drop_column('job_metrics', 'action_items')
    op.drop_column('job_metrics', 'work_life_balance_score')
    op.drop_column('job_metrics', 'career_growth_score')
    op.drop_column('job_metrics', 'financial_health_score')
    op.drop_column('job_metrics', 'risk_factors')
    op.drop_column('job_metrics', 'overall_recommendation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_metrics', sa.Column('overall_recommendation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_metrics', sa.Column('risk_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('job_metrics', sa.Column('financial_health_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('job_metrics', sa.Column('career_growth_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('job_metrics', sa.Column('work_life_balance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('job_metrics', sa.Column('action_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('job_metrics', sa.Column('opportunities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('job_metrics', 'ai_analysis')
    # ### end Alembic commands ###
