"""add_job_metrics_ai_analysis_fields

Revision ID: ac661e467e04
Revises: dad1352eb4ca
Create Date: 2025-08-08 22:58:12.819920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac661e467e04'
down_revision: Union[str, Sequence[str], None] = 'dad1352eb4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_metrics', sa.Column('career_growth_score', sa.Float(), nullable=True))
    op.add_column('job_metrics', sa.Column('financial_health_score', sa.Float(), nullable=True))
    op.add_column('job_metrics', sa.Column('work_life_balance_score', sa.Float(), nullable=True))
    op.add_column('job_metrics', sa.Column('overall_recommendation', sa.String(), nullable=True))
    op.add_column('job_metrics', sa.Column('action_items', sa.JSON(), nullable=True))
    op.add_column('job_metrics', sa.Column('risk_factors', sa.JSON(), nullable=True))
    op.add_column('job_metrics', sa.Column('opportunities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_metrics', 'opportunities')
    op.drop_column('job_metrics', 'risk_factors')
    op.drop_column('job_metrics', 'action_items')
    op.drop_column('job_metrics', 'overall_recommendation')
    op.drop_column('job_metrics', 'work_life_balance_score')
    op.drop_column('job_metrics', 'financial_health_score')
    op.drop_column('job_metrics', 'career_growth_score')
    # ### end Alembic commands ###
